name: ai_function_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  ai_function:
    path: ../ai_function
  build: ^2.3.1
  dio: ^5.1.1
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
