name: ai_function_generator
description: A GPT-4 based code generator for Dart (see ai_function package)
version: 1.0.0
repository: https://github.com/gabfeudo/ai_function_generator

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  ai_function: ^1.0.0
  analyzer: ^5.10.0
  build: ^2.3.1
  dio: ^5.1.1
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
